Add github integration tests
SovereignCloudStack/cluster-stack-operator pull request #19
Opened 2023-10-06 05:48 UTC by nitisht

**What this PR does / why we need it**:
This PR adds integration tests to test the release asset download flow from github

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

2023-10-06 07:29 UTC, berendt commented
We use Zuul CI. The use of Github Actions should be avoided. I would prefer not to build everything on Github Actions first and then migrate it all.

Benjamin recently wrote a Zuul users guide. It's available at https://docs.scs.community/dev-docs/operations/operations/zuul-ci-cd-quickstart-user-guide.

A good example for the use of Zuul is in the https://github.com/SovereignCloudStack/k8s-cluster-api-provider repository.

I think someone from the Zuul team can also give a hands-on.

There is also a dedicated Matrix room: #scs-zuul:matrix.org

2023-10-06 18:22 UTC, janiskemper requested changes

2023-10-06 18:22 UTC, janiskemper commented on Makefile
> +.PHONY: test-unit-core
there is test-unit already!

2023-10-06 19:21 UTC, jschoone commented
> We use Zuul CI. The use of Github Actions should be avoided. I would prefer not to build everything on Github Actions first and then migrate it all.
> 
> Benjamin recently wrote a Zuul users guide. It's available at https://docs.scs.community/dev-docs/operations/operations/zuul-ci-cd-quickstart-user-guide.
> 
> A good example for the use of Zuul is in the https://github.com/SovereignCloudStack/k8s-cluster-api-provider repository.
> 
> I think someone from the Zuul team can also give a hands-on.
> 
> There is also a dedicated Matrix room: #scs-zuul:matrix.org

Thanks for raising this. We are aware of it but agreed to use GitHub Actions here to move faster. 
A later use of another CI tool is not such a big hassle. Due to the container meeting not taking place, I forgot to report. If there is any ambiguity, it should be deferred to an appropriate meeting.

2023-10-09 13:49 UTC, janiskemper commented
blocked by https://github.com/SovereignCloudStack/cluster-stack-operator/issues/20 and until there is a second release in [cluster-stacks](https://github.com/SovereignCloudStack/cluster-stacks) named docker-ferrol-1-27-v1

2023-10-12 07:42 UTC, nitisht commented
> blocked by #20 and until there is a second release in [cluster-stacks](https://github.com/SovereignCloudStack/cluster-stacks) named docker-ferrol-1-27-v1

Now that #20 is closed, can we take this in?

2023-10-12 07:47 UTC, janiskemper approved these changes

2023-10-12 07:47 UTC, merged